name: fourth workflow using github actions

run-name: >+
          fourth workflow
          ${{ github.actor }} has triggered this workflow \
          using ${{ github.event_name }} event \
          on branch ${{ github.ref }} from ${{ github.repository }} repo.

on:
  push:
    branches:
      - feature/*

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: checking out to repo
        uses: actions/checkout@v4
      - name: list files
        run: ls -la
      - name: print file content
        run: cat firstfile.txt

  second-fail-job:
    runs-on: ubuntu-latest
    steps:
      - name: echo some text
        run: echo "hey there guyssssssssssssssssssssssssssssssssssssssssssssss......"
      - name: print file content
        run: cat firstfile.txt

  third-notification-job:
    runs-on: ubuntu-latest
    needs: second-fail-job
    if: always()
    steps:
      - name: notification about second job failure
        if: ${{needs.second-fail-job.result == 'failure' }}
        run: echo "second job failed, sending notification to dev team"
      - name: notification about second job success
        if: ${{ needs.second-fail-job.result == 'success' }}
        run: echo "hurrayyyyyyyyyyy! second job successfull........."
      - name: job status
        if: always()
        run: echo "Second Job result status is ${{needs.second-fail-job.result}}"
